name: health_hero
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  cupertino_icons: ^1.0.0
  provider: ^5.0.0
  flutter_dotenv: ^5.0.2
  shared_preferences: ^0.5.12+4
  youtube_player_flutter: ^8.0.0
  permission_handler: ^5.0.1+1
  image_gallery_saver: ^1.7.1
  fl_chart: ^0.40.0
  intl: ^0.17.0
  # tflite: 1.1.2
  image_picker: 0.7.4
  quiver: ^3.0.1+1
  image: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/models/labels.txt
    - assets/models/model.tflite
  fonts:
    - family: SinhalaMN
      fonts:
        - asset: assets/fonts/SinhalaMN-Regular.ttc
          weight: 200
